[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stitchx_sid = "Gvob5UYJiC2EvqFW6xgyq15EEypp3YpFy2G1La6rctnC"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
